### ISSUE TITLE
Unsuccessful usage 

### ISSUE THREAD

**Issue by Yuujiso** [leiblyh/osubannergrabber#1]
Hello, I just tried to grab a banner from (https://osu.ppy.sh/beatmapsets/842412) and from (https://osu.ppy.sh/beatmapsets/1718302#osu/3511456). The result was unsuccessful. Probably osu! changed the way to store a banners for beatmaps. Or there are such beatmaps that can't be grabbed.

**Comment by leiblyh** [comment]
All fixed, thanks for pointing this out! Turns out when I pushed this to github I had made some mistakes with how banners were stored which caused it to break.
